spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/netplix?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    open-in-view: false
    show-sql: true
  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true